#!/usr/bin/env python3
"""
This script lists all databases in a MongoDB instance.
"""

from pymongo import MongoClient


def list_databases():
    """
    Connect to MongoDB and list all databases.

    Returns:
        list: A list of database names.
    """
    client = MongoClient()
    databases = client.list_database_names()
    return databases

if __name__ == "__main__":
    for db in list_databases():
        print(db)
